name: Continuous Integration

on: push

permissions:
  contents: read

jobs:
  typespec:
    name: check typespec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir 
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.15.4
        otp-version: 26.0.2
    - name: Restore PLT cache
      uses: actions/cache/restore@v3
      id: plt_cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-plt
        restore-keys: ${{ runner.os }}-plt
    - name: Create PLTs
      if: steps.plt_cache.outputs.cache-hit != 'true'
      run: mix dialyzer --plt
    - name: Save PLT cache
      uses: actions/cache/save@v3
      if: steps.plt_cache.outputs.cache-hit != 'true'
      id: plt_cache_save
      with:
        key: ${{ runner.os }}-plt
        path: priv/plts
    - name: Run dialyzer
      run: mix dialyzer --format github

  formatter:
    name: check formatted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir 
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.15.4
        otp-version: 26.0.2
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-v2
        restore-keys: ${{ runner.os }}-mix
    - name: Checck Formatted
      run: mix format --check-formatted
  test:
    name: test ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["26.0.2"]
        elixir: ["1.15.4"]
    env:
      MIX_ENV: test
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 --name postgres
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir 
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-v2
        restore-keys: ${{ runner.os }}-mix
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
